  services:
    redis:
        image: redis:7-alpine
        container_name: redis
        volumes:
        - redis_data:/data 
        - ./redis.conf:/usr/local/etc/redis/redis.conf:ro 
        restart: unless-stopped
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 5s
          timeout: 5s
          retries: 3

    caching-proxy:
      env_file:
          - docker.env
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "${PROXY_PORT}:${PROXY_PORT}"
      environment:
        - PORT=${PROXY_PORT}
        - TARGET_URL=${TARGET_URL}
        - REDIS_ADDR=${REDIS_ADDR}
      depends_on:
        - redis
      restart: unless-stopped 
      healthcheck:  
        test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
        interval: 30s
        timeout: 5s
        retries: 3
    
  networks:
    default: 
      driver: bridge

  volumes:
    redis_data:

